### ISSUE TITLE
Mega Menu Issue

### ISSUE THREAD

**Issue by sudharsank** [LiveTiles/CodeSnippetGallery#3]
I tried using the MegaMenu Code Snippet from the code snippet gallery and facing some issues while displaying the mega menu.
Below are the steps followed.
1. Added the Code Snippet tile on to a Nested Row
2. Copied the MegaMenu snippet on to the 'Code' section in the 'Code Snippet Tile.'
3. Saved and verified the MegaMenu, but nothing appears, and there are lots of issues on the browser console.

Also, would like to know whether the CSS and script files referred in the MegaMenu snippets are pre-loaded with LiveTiles.

**Comment by trey-miller** [comment]
Hi @sudharsank , I'm not sure how that MegaMenu code snippet got in there but it was not a usable script. It was referencing files that were not public, and doing little else. I've deleted the code snippet from this repository. I apologize for the inconvenience.
